language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install pkg-config libsrtp0 libsrtp0-dev
  - wget http://www.pjsip.org/release/2.3/pjproject-2.3.tar.bz2
  - tar jxf pjproject-2.3.tar.bz2
  - pushd pjproject-2.3
  - ./configure
  - make dep
  - make clean
  - make
  - make install
  - popd
  - ls -1 /usr/local/include
  - ls -1 /usr/local/lib
  - ls -1 /usr/lib/pkgconfig
script:
  - mkdir tmp
  - pushd tmp
  - cmake ..
  - make && ./tests/test-pjsettings
  - popd
os:
  - linux