language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install aptitude
  - aptitude search pj
  - sudo apt-get update
  - sudo apt-get install pjsip
  - sudo apt-get install pkg-config
script: cmake && make
os:
  - linux