language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install pkg-config libboost-all-dev
script:
  - mkdir tmp
  - pushd tmp
  - cmake ..
  - make && pushd tests && ./test-pjsettings && popd
  - popd
os:
  - linux