version: 1.0.{build}
skip_tags: true
clone_folder: c:\projects\pjsettings
environment:
  PJSIP_ROOT: c:\projects\pjproject
  PJSETTINGS_ROOT: c:\projects\pjsettings
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
install:
  - if "%PLATFORM%" == "x86" set PLATFORM=Win32
  - git clone https://github.com/halex2005/pjproject.git %PJSIP_ROOT%
  - set
  - pushd %PJSIP_ROOT%
  - msbuild pjproject-v120.sln /t:pjproject
  - popd
  - mkdir %PJSETTINGS_ROOT%\tmp
  - pushd %PJSETTINGS_ROOT%\tmp
  - if "%%"=="x64" cmake .. -G "Visual Studio 12 Win64" else cmake .. -G "Visual Studio 12"
build:
  project: c:\projects\pjsettings\tmp\Project.sln
