version: 1.0.{build}
skip_tags: true
clone_folder: c:\projects\pjsettings
os: unstable
environment:
  INSTALL_PREFIX: c:\Libraries
  BOOST_ROOT: c:\Libraries\boost
  PJSIP_SOURCES_ROOT: c:\projects\pjproject
  PJSIP_ROOT: c:\projects\pjproject
  PJSETTINGS_ROOT: c:\projects\pjsettings
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
install:
  - if "%PLATFORM%" == "Win32" set CMAKE_GENERATOR="Visual Studio 12"
  - if "%PLATFORM%" == "x64"   set CMAKE_GENERATOR="Visual Studio 12 Win64"
  - if "%PLATFORM%" == "Win32" set BOOST_DEFINITIONS=-DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_ROOT%/lib32-msvc-12.0"
  - if "%PLATFORM%" == "x64"   set BOOST_DEFINITIONS=-DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_ROOT%/lib64-msvc-12.0"
  - git clone https://github.com/halex2005/pjproject.git %PJSIP_SOURCES_ROOT%
  - mkdir "%PJSIP_SOURCES_ROOT%\tmp"
  - cd "%PJSIP_SOURCES_ROOT%\tmp"
  - cmake .. -G %CMAKE_GENERATOR% -DCMAKE_INSTALL_PREFIX="%INSTALL_PREFIX%"
  - msbuild pjproject.sln
  - msbuild INSTALL.vcxproj
  - set PJSIP_ROOT=%INSTALL_PREFIX%\pjproject
  - mkdir "%PJSETTINGS_ROOT%\tmp"
  - cd "%PJSETTINGS_ROOT%\tmp"
  - cmake .. -G %CMAKE_GENERATOR% %BOOST_DEFINITIONS%
build:
  project: c:\projects\pjsettings\tmp\pjsettings.sln
before_test:
  - cd "%PJSETTINGS_ROOT%\tmp" && ctest -C %Configuration%
