version: 1.0.{build}
skip_tags: true
clone_folder: c:\projects\pjsettings
environment:
  PJSIP_ROOT: c:\projects\pjproject
  PJSETTINGS_ROOT: c:\projects\pjsettings
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
install:
  - git clone https://github.com/halex2005/pjproject.git %PJSIP_ROOT%
  - set
  - mkdir %PJSETTINGS_ROOT%\tmp
  - pushd %PJSETTINGS_ROOT%\tmp
  - if "%%"=="x64" cmake .. -G "Visual Studio 12 Win64" else cmake .. -G "Visual Studio 12"
build:
  project: %PJSIP_ROOT%\pjproject-v120.sln
  project: %PJSETTINGS_ROOT%\tmp\Project.sln
